### ISSUE TITLE
Additional/non-existent parameters in the likelihood function are accepted without error.

### ISSUE THREAD

**Issue by kevinchern** [UBC-Stat-ML/blangSDK#129]
Example for a likelihood function `Exponential(rate)`:

Expected behaviour:

`x ~ Exponential(1.0, 123)` should cause an error.

Actual behaviour:
`x ~ Exponential(1.0, 123)`  is treated as

`x ~ Exponential(1.0)`

**Comment by alexandrebouchard** [comment]
Thanks! Indeed that should be prioritized
