### ISSUE TITLE
Improve error message to indicate inappropriate data type. (ie. Plated<Integer> versus Plated<IntVar>)

### ISSUE THREAD

**Issue by kevinchern** [UBC-Stat-ML/blangSDK#131]
Lacking indication of error caused by misusing Plated\<Integer\> over Plated\<IntVar\>.
To reproduce:
1. Declare Plated\<Integer\> variable `x`
2. Run inference on a dataset with `x=na` (missing) values.

**Comment by alexandrebouchard** [comment]
There are some improvements about this in update 1.27.0
