### ISSUE TITLE
Different gradle versions can break blang CLI

### ISSUE THREAD

**Issue by kevinchern** [UBC-Stat-ML/blangSDK#137]
(Needed for reproducibility)

# Problem:
blang CLI fails to compile individual `.bl` files.
```
...
FAILURE: build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':generateXtext'.
> Could not resolve all dependencies for configuration ':xtextLanguage'.
...
```

# How to Reproduce:
1. Install `gradle 4.4.1` (This is latest gradle version for Ubuntu without additional ppa)
2. `git clone https://github.com/UBC-Stat-ML/blangSDK/`
3. build the sdk
4. run a `.bl` file with `blang` binary generated from sdk build (step 3).

**I suspect the issue is caused by:**
`StandaloneCompiler.runGradle(...)` uses gradle cmd, which fails to compile. The standalone compiler should probably use a graddle wrapper(?)

Installing gradle 5.4.1 fixes this problem, however, an additional PPA is required to install this version.

**Comment by alexandrebouchard** [comment]
OK, I think I can push a fix on this later tonight...

**Comment by alexandrebouchard** [comment]
It's a bit simpler than I thought.

**Comment by alexandrebouchard** [comment]
Give it a try now, it should be robust to the host gradle version.
