### ISSUE TITLE
Inconsistent HDI in posterior plot and table summary

### ISSUE THREAD

**Issue by chiukenny** [UBC-Stat-ML/blangSDK#163]
The HDI that is in summaries does not match the red line on the posterior plot for the BasicReparameterized model in [this tutorial](https://www.stat.ubc.ca/~bouchard/courses/stat520-sp2020-21/Hierarchical_models.html). For μ=0.5, the summary reports an upper HDI of 0.452, but the plot shows an upper value >0.5.

![image](https://user-images.githubusercontent.com/18079075/106041074-31ae5d80-6090-11eb-94a5-45b9599a770f.png)

To reproduce: run Exercise 1 in [the tutorial](https://www.stat.ubc.ca/~bouchard/courses/stat520-sp2020-21/Hierarchical_models.html).

**Comment by alexandrebouchard** [comment]
@kevinchern sorry to add another thing to you plate, but do you mind looking at this when you have a chance? Thank you!

**Comment by kevinchern** [comment]
:O.... on it!

**Comment by alexandrebouchard** [comment]
Thanks!

**Comment by kevinchern** [comment]
Looks like the current plotting template automatically includes a burn-in, whereas summaries do not.
I think we should make burn-ins consistent across outputs, or label the plots to indicate burn-in has been applied.
Also worth considering setting the default to 0 burn-in instead of 0.5.

**Comment by alexandrebouchard** [comment]
Most plot actually discard burn in right now. For example, in the posterior plotting code, the line

https://github.com/UBC-Stat-ML/blangSDK/blob/6b4b47fcef3fcf6c326c264d594ddfe90c2c773d/src/main/java/blang/runtime/internals/DefaultPostProcessor.xtend#L434

triggers the following which removes the burn in samples:

https://github.com/UBC-Stat-ML/blangSDK/blob/6b4b47fcef3fcf6c326c264d594ddfe90c2c773d/src/main/java/blang/runtime/internals/DefaultPostProcessor.xtend#L518

Ah I see, it's actually the other way around: summaries don't remove the burn in right now:

https://github.com/UBC-Stat-ML/blangSDK/blob/6b4b47fcef3fcf6c326c264d594ddfe90c2c773d/src/main/java/blang/runtime/internals/DefaultPostProcessor.xtend#L589

I think adding the burn in macro should do it. Do you mind giving it a try? Thanks again!

**Comment by kevinchern** [comment]
Yep! Discarding burn-in from summaries gives consistent results.

**Comment by alexandrebouchard** [comment]
Resolved in https://github.com/UBC-Stat-ML/blangSDK/pull/164
