### ISSUE TITLE
How to parallelize multiple-try?

### ISSUE THREAD

**Issue by garyzhubc** [UBC-Stat-ML/blangSDK#88]
How to parallelize multiple-try (or neighbourhood traversal)? It seems the best is to re-structure the engine interface. Although such parallelization may not have significant impact on the performance.

**Comment by alexandrebouchard** [comment]
You can go a bit higher level and create a new implementation of the blang.mcmc.Sampler interface. 

For parallelization, I recommend using BriefParallel.process. You can find an example in AdaptiveJarzynski

**Comment by alexandrebouchard** [comment]
This does not seem to be a blang specific issue.
